# Setup a redis server
version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network
    restart: always
  redis-cli:
    image: redis:latest
    container_name: redis-cli
    depends_on:
      - redis
    networks:
      - redis_network
    restart: always
    entrypoint: ["redis-cli", "-h", "redis"]