# Setup a redis server
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network
    restart: always
    # You could add command here to configure Redis (optional)
    # command: ["redis-server", "--requirepass", "yourpassword"]
    
  redis-cli:
    image: redis:latest
    container_name: redis-cli
    depends_on:
      - redis
    networks:
      - redis_network
    restart: always
    entrypoint: ["redis-cli", "-h", "redis"]

networks:
  redis_network:
    driver: bridge

volumes:
  redis_data:
    driver: local
